#!/usr/bin/env python3
"""faster-whisper example.

Usage:
    python examples/stt_example.py
    python examples/stt_example.py --audio path/to/audio.wav
"""

from __future__ import annotations

import argparse
from pathlib import Path

from faster_whisper import WhisperModel


ROOT = Path(__file__).resolve().parents[1]
MODEL_DIR = ROOT / "3rdParty" / "models" / "faster-whisper-small"
DEFAULT_AUDIO = ROOT / "examples" / "out" / "tts_en.wav"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Transcribe audio with faster-whisper.")
    parser.add_argument(
        "--audio",
        type=Path,
        default=DEFAULT_AUDIO,
        help="Audio file to transcribe. The default is generated by tts_example.py.",
    )
    parser.add_argument(
        "--device",
        default="cpu",
        choices=("cpu", "cuda"),
        help="Use cpu for lowest VRAM, cuda for faster inference.",
    )
    parser.add_argument(
        "--compute-type",
        default="int8",
        help="faster-whisper compute type, for example int8 or float16.",
    )
    parser.add_argument("--language", default="en", help="Language code.")
    parser.add_argument(
        "--text-only",
        action="store_true",
        help="Print only the transcribed text so it can be passed to the LLM.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.audio.exists():
        raise FileNotFoundError(
            f"{args.audio} does not exist. Run examples/tts_example.py first "
            "or pass --audio path/to/audio.wav."
        )

    model = WhisperModel(
        str(MODEL_DIR),
        device=args.device,
        compute_type=args.compute_type,
    )
    segments, info = model.transcribe(
        str(args.audio),
        language=args.language,
        beam_size=1,
        vad_filter=True,
    )

    segments = list(segments)
    if args.text_only:
        print(" ".join(segment.text.strip() for segment in segments))
        return

    print(f"Detected language: {info.language} ({info.language_probability:.2f})")
    for segment in segments:
        print(f"[{segment.start:6.2f}s -> {segment.end:6.2f}s] {segment.text.strip()}")


if __name__ == "__main__":
    main()
